### PR TITLE
add IPv4 class finder in C

### PR DESCRIPTION
**Pull request by abrahamfrancis**
Resolves Issue #166 

### Description
Added an IPv4 class identifier in C

### How to run
Compile the C code.
The input and output format are exactly as mentioned in the Issue Statement.

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Followed the Contributing guidelines

### CODE REVIEW

**Comment by abrahamfrancis** [comment]
@krithikvaidya

**Comment by krithikvaidya** [comment]
Great work, there's a small bug though - if I give the input as, say, `192.168.100.12345678` it'll recognize it as a valid address... even if I send `192.168.100.232abcdefg` as the input, it'll again be recognised as valid... can you figure out why?

**Comment by abrahamfrancis** [comment]
Yes, because I am only reading upto the first 15 characters.

Ok, I'll fix that.

**Comment by abrahamfrancis** [comment]
I know this is not a perfect fix. But now, I am checking for non numeric characters that may be in the IP string. And I am reading the first 1023 characters :)

**Pull request merged**
