### PR TITLE
Added IP Address Classification Program in Golang

### PR DESCRIPTION
**Pull request by AdiY2j**
Resolves Issue #166

### Description
Program to classify IP Address in Golang

### Technical Specifications
Golang

### How to run

1] Use online editor https://repl.it/languages/go (Replit) . Copy , Paste and just Run it

2] Download the Golang.go file and save it on Desktop. Use cmd :
 a] Go to particular directory where file is stored. 
 b] Use command : go build  (It will generate Golang.exe file)
 c] Use command : Golang  (It will run Program)

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.

### CODE REVIEW

**Comment by krithikvaidya** [comment]
Hey, good job! Just place the folder in the systems/ directory, and it'll be merged.

**Comment by AdiY2j** [comment]
@krithikvaidya Please merge the file as I have placed it inside systems/ folder. You can review my PR and merge it. Thanks

**Comment by SaurabhAgarwala** [comment]
@krithikvaidya Cant this be merged now?

**Comment by krithikvaidya** [comment]
Yeah merge it @SaurabhAgarwala

**Pull request merged**
