### PR TITLE
I have solved the issue

### PR DESCRIPTION
**Pull request by him1anshu**
Resolved Issue #1 

Description:
Introduction file is added.

### CODE REVIEW

**Comment by him1anshu** [comment]
resolved issue #41 
Description
created a c++ program to calculate the strength of a given password and to tell the user how he/she can make it strong.

**Comment by SkaMessi10** [comment]
The program you have added does not work for the condition of consecutive alphabets/numbers in some case.
For example, if my password is CrazyBoy1@,the strength should be 8..but it is displaying 6.
Pleas make the respective changes.

**Comment by him1anshu** [comment]
(3)The password should not have more than 3 consecutive digits or alphabets. For example, a substring 1234 or abcd makes the password weaker.(2 points)

this point in the program says that if there are more than 3 consecutive digits or alphabets then the password will get weaker and in your input, there are 4 consecutive alphabets (razy) , so 2 points will be deducted and the output will be 6 only.

**Comment by him1anshu** [comment]
resolved issue #51 

Description:

Created a C program which converts decimal to binary without using in-built function.

**Comment by NJnisarg** [comment]
@him1anshu One PR should solve one issue. Please keep this PR for #1 . Create separate PR for other issues you are solving. Remove all other files for this and create separate PRs for other files.

**Pull request closed without merging**
