### PR TITLE
Intro + Login Script

### PR DESCRIPTION
**Pull request by tharun634**
Resolves Issue #1 

### Description
Added details of myself

### CODE REVIEW

**Comment by tharun634** [comment]
@SaurabhAgarwala  Please review my PR for issue #1 .

**Comment by tharun634** [comment]
Resolves issue #46 
**Description**
Script to automate login of SOPHOS using POST request

**Comment by NJnisarg** [comment]
@tharun634 This PR should be solving only one issue. I suggest you keep this PR for #1 and make a new PR for #46 . Remove the file for #46 and then tag me again, I will merge it.

**Comment by SaurabhAgarwala** [comment]
> @SaurabhAgarwala Please review my PR for issue #1 .

@tharun634 All PRs for #1 has been rendered valid. Please make a separate PR for #46

**Pull request closed without merging**
