### PR TITLE
Login

### PR DESCRIPTION
**Pull request by adityagamer786**
Resolves Issue #132 

### Description
Created a login page
which will alert at 5 wrong attempts
and stop you at 10 wrong attempts

### Technical Specifications
JS ES6

### How to run
Open index.html using a web browser

### CODE REVIEW

**Comment by adityagamer786** [comment]
@harshagrwl please review my code

**Comment by SaurabhAgarwala** [comment]
@harsagrwl Can this be merged?

**Comment by harshagrwl** [comment]
> @harshagrwl Can this be merged?

Yes, It can be merged. I have reviewed the code. But, the issue is already closed by another PR.

**Comment by harshnitk17** [comment]
Since @adityagamer786  has already coded for this issue , I am merging both (i.e. the old and this PR)  into repo

**Pull request merged**
