### PR TITLE
Issue 166- IPv4 Address Class Code

### PR DESCRIPTION
**Pull request by nirmalhk7**
Resolves Issue #166 

### Description
This application finds the class of an IP address. 

### Technical Specifications
Made with C++, the program uses regex expression for an IPv4 address to validate the address entered.

### How to run
**Linux**
- Navigate to 

> systems/Issue 166-IPv4 Class

- In your terminal do 

> g++ cplusplus.cpp

- Type 

> ./a.out

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by nirmalhk7** [comment]
@krithikvaidya Please review.

**Comment by nirmalhk7** [comment]
Anyone @WebClubNITK, please review this PR. Thanks!

**Comment by nirmalhk7** [comment]
@krithikvaidya :smiley:

**Comment by nirmalhk7** [comment]
> Hey, sorry for the delay... the program looks good, just rename the folder to `Issue 166 - IPv4 Class` (with the space before and after the hyphen) to avoid creating a new folder.

Done.

**Comment by nirmalhk7** [comment]
@NJnisarg @krithikvaidya Please review & merge. Thanks!

**Comment by SaurabhAgarwala** [comment]
@NJnisarg @krithikvaidya Please review it

**Comment by krithikvaidya** [comment]
A few .vscode files got added in your later commits...  
It's fine though, please merge it @SaurabhAgarwala

**Pull request merged**
