### PR TITLE
Conversion

### PR DESCRIPTION
**Pull request by Ashwin901**
Resolves Issue #51

### Description
Conversion of decimal number to binary

### Technical Specifications
While loop

### CODE REVIEW

**Comment by SaurabhAgarwala** [comment]
@shantanu9 Please review it

**Comment by shanthanu9** [comment]
This is @deepakkavoor's issue.

**Comment by deepakkavoor** [comment]
@Ashwin901 your code doesn't compile. Also, change the file extension from .c.txt to .c

**Comment by deepakkavoor** [comment]
@Ashwin901 You haven't corrected dec2bin.c 
It still gives compilation error
Also, when pushing to the pr, make sure there are no conflicts

**Comment by Ashwin901** [comment]
> @Ashwin901 your code doesn't compile. Also, change the file extension from .c.txt to .c

I have created a new pull request and corrected the mistakes please review

**Comment by Ashwin901** [comment]
> @Ashwin901 You haven't corrected dec2bin.c
> It still gives compilation error
> Also, when pushing to the pr, make sure there are no conflicts

I have created a new pr and corrected the mistakes plz review

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Thanks for contributing. Closing the PR.

**Pull request closed without merging**
