### PR TITLE
Updated login.py

### PR DESCRIPTION
**Pull request by tharun634**
Resolves Issue #46 

### Description
Script to automate login process for NITK-NET

### How to run
Just replace placeholders with credentials, save and run.

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts

### CODE REVIEW

**Comment by tharun634** [comment]
@NJnisarg Is this PR fine. I am not sure with the branching systems, I've tried my best to create a branch and request a PR.

**Comment by SaurabhAgarwala** [comment]
@NJnisarg Please review it

**Comment by SaurabhAgarwala** [comment]
@krithik-vaidya @NJnisarg Please review it

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Thanks for contributing. Closing the PR.

**Pull request closed without merging**
