### PR TITLE
form validation

### PR DESCRIPTION
**Pull request by bilalbutt044**
Resolves Issue #36 

### Description

made three functions called `validateForm` `validEmail` `validPhoneNumber`

`validEmail` method is used to check if an email is valid or not. If email is not valid it shows an alert with the message `invalid email formate`. I used regex for email validation. 

`validPhoneNumber` method is used to check if phone number is valid or not. If a phone number is not valid it shows an alert with the message `invalid phone number formate`. I used regex for phone number validation. 

`validateForm` in this method I made a valuable called `check` which value we update with return value from both above function. if formate is not valid we return `false` and this `false` saved in check variable which then passed to form.
### How to run
copy this path of `BilalJsformValidation.html` which is located in `development/form validation`.
paste path in browser the file will open.

### Checklist
- [ ] Code compiles correctly.
- [ ] Changes are tested properly.
- [ ] Added the README / documentation, if necessary.
- [ ] Followed the Contributing guidelines.
- [ ] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by bilalbutt044** [comment]
when my PR will accept? @Chans321

**Comment by Chans321** [comment]
Hey, i finished reviewing your code. Good job. Your pr will be merged soon.

**Comment by bilalbutt044** [comment]
Will this pull request count for #hactoberfest competition?

**Comment by niranjanrao1509** [comment]
@bilalbutt044  Yes!

**Pull request merged**
