### PR TITLE
Test3

### PR DESCRIPTION
**Pull request by Ashwin901**
Resolves Issue #51 

### Description
Conversion of decimal number to binary.

### CODE REVIEW

**Comment by deepakkavoor** [comment]
It is preferred that you send one pr per issue. Otherwise, I have to wait till others review your alphabet conversion and exponent. 

One more thing, you can push changes you make to your existing pr, you don't have to create a new one.

Please make separate prs for each issue, and delete all these redundant ones.

**Comment by Ashwin901** [comment]
> It is preferred that you send one pr per issue. Otherwise, I have to wait till others review your alphabet conversion and exponent.
> 
> One more thing, you can push changes you make to your existing pr, you don't have to create a new one.
> 
> Please make separate prs for each issue, and delete all these redundant ones.

Okay.....I will make sure I don't repeat this

**Comment by Ashwin901** [comment]
> It is preferred that you send one pr per issue. Otherwise, I have to wait till others review your alphabet conversion and exponent.
> 
> One more thing, you can push changes you make to your existing pr, you don't have to create a new one.
> 
> Please make separate prs for each issue, and delete all these redundant ones.

And how do u delete the files which r already committed

**Comment by deepakkavoor** [comment]
Look at either git rm, or git reset depending on what you want to do.
Please delete these prs later, conversion, test2 and test3

**Comment by Ashwin901** [comment]
> Look at either git rm, or git reset depending on what you want to do.
> Please delete these prs later, conversion, test2 and test3

okay

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Thanks for contributing. Closing the PR.

**Pull request closed without merging**
