### PR TITLE
Add Optimised Number of pairs #12

### PR DESCRIPTION
**Pull request by lelloman**
Resolves Issue #12

### Description
The algorithm is pretty simple, it requires 3 variables and one loop, the time complexity is O(n) and space complexity is O(1). 
A left and right cursor are initialized to the extremes elements of the array, then the loop is repeated until the 2 cursors overlap. In each iteration the elements in the array pointed by the cursor are summed, if the sum is equal to the target, the count of pairs is increased by 1 and the cursor are moved toward the center of the array. If the sum is above the target then the right cursor is moved to the left by 1 position, this is because the array is sorted so we are sure that by moving the right cursor to the left the sum at the next iteration will decrease. If the sum is below target the opposite operation is performed on the left cursor.

### How to run
Please see [READ_ME.txt](https://github.com/WebClub-NITK/Hacktoberfest-2k19/blob/master/algorithms/12/READ_ME.txt)

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by SaurabhAgarwala** [comment]
@namanmanish Please review the PR and add your comments here

**Comment by namanmanish** [comment]
It seems good.Running fine and in linear time.Set to be merged.

**Comment by GuptaNCode** [comment]
i want to work on this project

**Comment by SaurabhAgarwala** [comment]
@GuptaNCode The issue has already been closed. Please look for other issues in the repo

**Pull request merged**
