### PR TITLE
Database Integration

### PR DESCRIPTION
**Pull request by adityagamer786**
Resolves Issue #63

### Description
It takes information about student registering in NITK and stores in SQLite DB

### Technical Specifications
DJango
### How to run
Please list all the steps required to run in details. Preferably specify steps for all platforms.
Install django
Install python3 (wont work on python2)
In terminal type python3 manage.py runserver

### CODE REVIEW

**Comment by adityagamer786** [comment]
Done

**Comment by SaurabhAgarwala** [comment]
@viveshCodes Please review it

**Comment by viveshCodes** [comment]
@adityagamer786  ,it seems you've removed the files . Please place it back  so that we can review it.
And if there's any doubt you want to ask,leave a comment here itself.

**Comment by NJnisarg** [comment]
I believe the issue specifically wants you to work with a database. Your login flow looks fine, but make it connected to some database(maybe sqlite, since it is embedded). Make the changes and add more commits

**Pull request merged**
