### PR TITLE
Prasad Intoduction

### PR DESCRIPTION
**Pull request by Prasad-g-maladkar**
Resolves Issue #<1>

### Description
introduction

### CODE REVIEW

**Comment by SaurabhAgarwala** [comment]
All PRs for issue 1 are being rendered as invalid

**Comment by Prasad-g-maladkar** [comment]
will i have to pull 4 more requests
as my only introduction pull request is invalid
WHAT IS LAST DAY TO SUBMIT

**Comment by Prasad-g-maladkar** [comment]
can u please provide ur whatsapp no.

**Comment by SaurabhAgarwala** [comment]
Only introduction PR is invalidated. Rest all PRs are considered.
For other doubts, you can discuss it over the Open Source@NITK Telegram Channel

**Pull request closed without merging**
