### PR TITLE
Created a Artifical Neural Network

### PR DESCRIPTION
**Pull request by kampaitees**
Here I used the hourly_wages_data.csv file whichis availabe in the data folder
The task is to predict the salary of the employee using deep learning

### CODE REVIEW

**Comment by kampaitees** [comment]
Bro review this and merge it

**Comment by SaurabhAgarwala** [comment]
@kampaitees Please review it.

**Comment by kampaitees** [comment]
> @kampaitees Please review it.

Bhai I only created the pull request

**Comment by SaurabhAgarwala** [comment]
@kampaitees Sorry for the confusion.

**Pull request merged**
