### PR TITLE
Fibonacci

### PR DESCRIPTION
**Pull request by codebreaker-00**
Resolves Issue #48 

### Description
I implimented a fibonacci series code it covers more range as it uses long long int.

### Technical Specifications
done in c programming language.

### How to run
compile,enter the value of n, get output.

### Checklist
- [ **] Code compiles correctly.
- [ **] Changes are tested properly.
- [ ] Added the README / documentation, if necessary.
- [ **] Followed the Contributing guidelines.
- [ **] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by shanthanu9** [comment]
Good work! Following are some suggestions:
- Don't include ```a.out``` in the PR.
- You have renamed ```fib.cpp``` to ```fibonacci.c```. Please implement your code in ```fib.cpp``` file itself.
- You have removed ```fib``` function. Don't remove it, just modify it to add your optimization.

**Comment by codebreaker-00** [comment]
Ok sir I will do that as soon as possible.

**Comment by shanthanu9** [comment]
Hey! PR #250 was made for the same issue and has successfully completed the task. Hence I will be merging that PR and closing the issue. Thanks for making a PR to this issue!

**Comment by codebreaker-00** [comment]
Ok sir, sorry for the inconvenience due to the mistakes in PR I did.

**Comment by shanthanu9** [comment]
That's totally fine! You did pretty good with the PR. Keep up the good work
and keep making more PRs!

PS: Don't address me as sir :P

**Pull request closed without merging**
