### PR TITLE
Add prime number generator

### PR DESCRIPTION
**Pull request by jilloestreicher**
esolves Issue #<issue_number>

### Description
Please explain the changes you made in detail here.

### How to run
Please list all the steps required to run in details. Preferably specify steps for all platforms.

### Checklist
- [ ] Code compiles correctly.
- [ ] Changes are tested properly.
- [ ] Added the README / documentation, if necessary.
- [ ] Followed the Contributing guidelines.
- [ ] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by SaurabhAgarwala** [comment]
@jilloestreicher Please specify the issue number which this PR solves.

**Comment by jilloestreicher** [comment]
Issue #139

**Comment by SaurabhAgarwala** [comment]
139 is the PR number. Please go to Issues tab, find the issue and tag its number here. Also, request a review from the issue creator

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Thanks for contributing. Closing the PR.

**Pull request closed without merging**
