### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by Akshayy99**
Resolves Issue #43 

### Description
Added a C++ program to find the binomial coefficient using Dynamic Programming.

### Technical Specifications
compiler: g++
nCr

### How to run
1. g++ nCrDynProg.cpp
2. ./a.out
3. enter n:
   enter r:

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [ ] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by abrahamfrancis** [comment]
I'm not sure if we can use bits/stdc++ as it is platform specific.

**Comment by Akshayy99** [comment]
Updated it. Kindly check. Replaced with standard headers.

**Comment by SaurabhAgarwala** [comment]
@Akshayy99 Since you have already coded it and in quite an efficient way so we will consider your PR for merging. Please solve the merge conflict by modifying the folder name a bit or making a new subfolder. 
@niranjansy Please review the PR accordingly when the changes are done.

**Comment by SaurabhAgarwala** [comment]
Hacktoberfest 2019 ends. Thanks for contributing. Closing the PR.

**Pull request closed without merging**
