### PR TITLE
Resolved issue housing price prediction #234

### PR DESCRIPTION
**Pull request by Shuddhatm22**
Resolves Issue #234 

### Description
Used linear Regression model 
Used R2_score and mean square error for evaluation
visualized using dist plot and correlation matrix

### CODE REVIEW

**Comment by Shuddhatm22** [comment]
please review this issue

**Comment by SaurabhAgarwala** [comment]
@SkaMessi10 Please review it

**Comment by SkaMessi10** [comment]
This works fine!
Great job!

**Comment by SkaMessi10** [comment]
@SaurabhAgarwala Please merge the issue.

**Pull request merged**
