### PR TITLE
coreected the segmentation fault

### PR DESCRIPTION
**Pull request by dipanshu231099**
esolves Issue #74 

### Description
i have made the new function merge and renamed the function merge_sort to merge. The merge function will merge two sorted arrays into a new array. Also i have added the check of len/2 to terminate the recursion when wanted

### How to run
Please list all the steps required to run in details. Preferably specify steps for all platforms.
simply run the source.c file and when it asks for input enter as it was inteded before...the output will come after the inputs are done.

### compilation
the code compiles proprely
`gcc source.c -o source` is what is to be done on the algorithms/74/ dir.

### CODE REVIEW

**Comment by narayanpai1** [comment]
Hey! We commend your enthusiasm and idea. But we are afraid we cannot merge this as the whole program is changed. This does not create any issues for small programs like this but it matters a lot when you are working with a huge codebase. Hence it is not considered as a good practice. 
Try to edit the pull request by just adding a few lines to the original code which fixes the error.
Here is a tutorial on how to edit a pull request
https://zellwk.com/blog/edit-pull-request/
All the best!!

**Comment by dipanshu231099** [comment]
> Hey! We commend your enthusiasm and idea. But we are afraid we cannot merge this as the whole program is changed. This does not create any issues for small programs like this but it matters a lot when you are working with a huge codebase. Hence it is not considered as a good practice.
> Try to edit the pull request by just adding a few lines to the original code which fixes the error.
> Here is a tutorial on how to edit a pull request
> https://zellwk.com/blog/edit-pull-request/
> Try to complete it by tomorrow noon.
> All the best!!

actually the code written earlier would be unable to detect many extreme test cases like when number of elements is 1 etc. one way is to rectify it by adding the extreme test cases other way is to make the code more general actually the code i changed had changed the names of varibales only and i have introduced a function 'merge' to do the while loop in your merge_sort....

What i can do is that i can rename the main function and pass to it the arguments as requested earlier.

**Comment by narayanpai1** [comment]
You just have to add the base case(number of elements is 1) for the recursive function

**Comment by dipanshu231099** [comment]
@narayanpai1 this time i have introduced 2 if statements and have kept the rest of the changes same as before

**Comment by narayanpai1** [comment]
Yes! This is what I was expecting.
But now there is another problem xD
Since u made the changes in your earlier submitted commit, the changes-log looks messy. There is one way out now. You can delete two recent commits in your repository and then make the changes and submit the pr as a single commit.

**Comment by dipanshu231099** [comment]
could i create a pr from a new branch if you wish

**Comment by dipanshu231099** [comment]
sir you may merge the pr i dont think their are too many commits as to that i require to stash them...actually i could not invest so much time in a particular task . I hope you understand sir.

**Comment by dipanshu231099** [comment]
is it merged sir?

**Comment by SaurabhAgarwala** [comment]
@narayanpai1 @Sagnik-Ghosh Please review it

**Comment by narayanpai1** [comment]
All good. It can be merged.

**Pull request merged**
